# Generated by Django 4.1 on 2022-09-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('house', models.CharField(max_length=20, null=True)),
                ('patronus', models.CharField(max_length=20, null=True)),
                ('wand_wood', models.CharField(max_length=20, null=True)),
                ('wand_core', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'characters',
            },
        ),
    ]
