# Generated by Django 4.1 on 2022-09-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='wand_core',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
