# Generated by Django 4.1 on 2022-09-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_name_alter_character_species_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='house',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
