# Generated by Django 4.1 on 2022-09-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('incantation', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('effect', models.TextField()),
                ('light', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'spells',
            },
        ),
    ]
