# Generated by Django 4.1 on 2022-09-03 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('chapters', '0002_alter_chapter_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
