# Generated by Django 4.1 on 2022-09-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('box_office_revenue', models.IntegerField()),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
